export function buildLiveEditor(input, font, emojiData, buildHighlight, presets) {
  const safeWidth = input.canvas.width - 2 * input.canvas.safeMargins.side;
  const data = JSON.stringify({input, emojiData, presets}).replaceAll('<', '\\u003c');
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Instagram highlight lab</title>
<style>
@font-face{font-family:AdFont;src:url(data:font/ttf;base64,${font});font-weight:${input.fontWeight}}
*{box-sizing:border-box}body{margin:0;font:15px/1.5 system-ui;background:#f3f3f3;color:#141414}main{display:flex;min-height:100vh}.controls{width:360px;flex-shrink:0;padding:28px;background:white;border-right:1px solid #ddd}h1{font-size:26px;line-height:1.15;margin:0 0 12px}p{margin:10px 0 22px}label{display:block;margin:16px 0 4px;font-size:13px;font-weight:600}input,select,textarea,button{font:inherit;border:1px solid #bbb;border-radius:5px;padding:8px;width:100%;background:white;color:#111}textarea{height:150px;resize:vertical}button{cursor:pointer;background:#111;color:white;margin-top:12px}input[type=color]{height:42px}.preview{flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:48px;overflow:auto;background:linear-gradient(135deg,#b7c8d2,#5d7278)}#stage{position:relative;flex-shrink:0;max-width:none}#stage svg{position:absolute;inset:0}.row{position:absolute;display:flex;justify-content:center;align-items:center;white-space:pre;font-family:AdFont;font-weight:${input.fontWeight}}.row img{flex-shrink:0}#metrics{font:13px/1.5 ui-monospace,monospace;margin-top:32px;max-width:800px;color:#111;background:#ffffffdf;padding:14px;border-radius:4px}#error{color:#9d1515}#measure{position:absolute;visibility:hidden;left:-10000px;top:0}.note{font-size:12px;color:#555}@media(max-width:800px){main{flex-direction:column}.controls{width:100%;border:0}.preview{padding:24px;min-height:500px}}
</style><main><section class="controls"><h1>Instagram highlight lab</h1><p>One measured outline, with rounded outward and inward corners. Edit text or spacing and it regenerates.</p>
<label for="block">Reference block</label><select id="block"></select><label for="copy">Copy — one line per row</label><textarea id="copy"></textarea>
<label for="size">Font size (px)</label><input id="size" type="number" min="44" max="100" step="1">
<label for="tracking">Letter spacing (%)</label><input id="tracking" type="number" min="-8" max="8" step="0.5" value="-3">
<label for="px">Horizontal padding (em)</label><input id="px" type="number" min="0" max="1" step="0.01">
<label for="py">Outer vertical padding (em)</label><input id="py" type="number" min="0" max="1" step="0.01">
<label for="line">Row height (em)</label><input id="line" type="number" min="1" max="2" step="0.01">
<label for="outer">Outer corner radius (em)</label><input id="outer" type="number" min="0" max="1" step="0.01">
<label for="inner">Inner corner radius (em)</label><input id="inner" type="number" min="0" max="1" step="0.01">
<label for="fill">Highlight fill</label><input id="fill" type="color"><button id="download">Download highlight SVG</button><button id="json">Download block settings</button><p id="error"></p><p class="note">Uses the bundled local TTF and emoji PNGs, with font loading awaited. Paper may use a different font version; its exact text widths can be supplied to the CLI. This tool does not modify Paper automatically.</p></section>
<section class="preview"><div id="stage"></div><div id="metrics"></div></section></main><div id="measure"></div>
<script>
const data=${data};
const buildHighlight=${buildHighlight.toString()};
const $=id=>document.getElementById(id);let result,svg,current;
function pieces(line){const a=[];for(const {segment:s} of new Intl.Segmenter('en',{granularity:'grapheme'}).segment(line)){if(data.emojiData[s])a.push({emoji:s});else if(a.length&&!a.at(-1).emoji)a.at(-1).text+=s;else a.push({text:s});}return a;}
function makeRow(line,size,tracking){const row=document.createElement('div');row.className='row';Object.assign(row.style,{position:'relative',width:'max-content',fontSize:size+'px',lineHeight:size+'px',letterSpacing:tracking+'em'});for(const part of pieces(line)){const el=document.createElement(part.emoji?'img':'span');if(part.emoji){el.src=data.emojiData[part.emoji];el.width=size;el.height=size;}else el.textContent=part.text;row.append(el);}return row;}
async function draw(){try{await document.fonts.load('${input.fontWeight} 46px AdFont');await document.fonts.ready;const size=Number($('size').value),tracking=Number($('tracking').value)/100,lines=$('copy').value.split('\\n');if(size<44)throw Error('Keep font size at least 44px.');if(lines.some(l=>!l.trim()))throw Error('Remove empty lines.');const measured=lines.map(line=>{const r=makeRow(line,size,tracking);$('measure').append(r);const w=r.getBoundingClientRect().width;r.remove();return w;});
const opts={textWidths:measured,rowHeight:size*Number($('line').value),paddingX:size*Number($('px').value),paddingY:size*Number($('py').value),outerRadius:size*Number($('outer').value),innerRadius:size*Number($('inner').value),mergeThreshold:size*0.10};result=buildHighlight(opts);const fill=$('fill').value;svg='<svg xmlns="http://www.w3.org/2000/svg" width="'+result.width+'" height="'+result.height+'" viewBox="0 0 '+result.width+' '+result.height+'"><path d="'+result.d+'" fill="'+fill+'"/></svg>';
$('stage').innerHTML=svg;$('stage').style.width=result.width+'px';$('stage').style.height=result.height+'px';lines.forEach((line,i)=>{const r=makeRow(line,size,tracking);Object.assign(r.style,{position:'absolute',width:(result.width-2*result.paddingX)+'px',height:result.rowHeight+'px',left:result.paddingX+'px',top:(result.paddingY+i*result.rowHeight)+'px',color:fill.toLowerCase()==='#ffffff'?'#000':'#fff'});$('stage').append(r);});
$('metrics').textContent='Text widths: '+measured.map(w=>w.toFixed(1)).join(' / ')+' px | Outline: '+result.width.toFixed(1)+' × '+result.height.toFixed(1)+' px | Tracking: '+(tracking*100)+'%';$('error').textContent=result.width>${safeWidth}?'Block exceeds the ${safeWidth}px safe width. Adjust line breaks; copy is preserved.':'';current={id:data.input.blocks[Number($('block').value)].id,lines,fontSize:size,fontFamily:data.input.fontFamily,fontWeight:data.input.fontWeight,letterSpacingEm:tracking,fill,geometry:{paddingXEm:Number($('px').value),paddingYEm:Number($('py').value),rowHeightEm:Number($('line').value),outerRadiusEm:Number($('outer').value),innerRadiusEm:Number($('inner').value)}};
}catch(e){$('error').textContent=e.message;result=null;}}
function select(){const b=data.input.blocks[Number($('block').value)],p={...data.presets[b.preset],...b.geometry};$('copy').value=b.lines.join('\\n');$('size').value=b.fontSize;$('fill').value=b.fill;$('tracking').value=data.input.letterSpacingEm*100;for(const [id,key]of [['px','paddingXEm'],['py','paddingYEm'],['line','rowHeightEm'],['outer','outerRadiusEm'],['inner','innerRadiusEm']])$(id).value=p[key];draw();}
data.input.blocks.forEach((b,i)=>{const o=document.createElement('option');o.value=i;o.textContent=b.id;$('block').append(o);});$('block').onchange=select;for(const id of ['copy','size','tracking','px','py','line','outer','inner','fill'])$(id).oninput=draw;
function save(content,name,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}$('download').onclick=()=>{if(result)save(svg,current.id+'-highlight.svg','image/svg+xml');};$('json').onclick=()=>{if(result)save(JSON.stringify(current,null,2),current.id+'-settings.json','application/json');};select();
</script></html>`;
}
